### ISSUE TITLE
Persistence ?

### ISSUE THREAD

**Issue by hanuka** [CakeDC/cakephp-oracle-driver#12]
Does it have a persistance parameter ? I would like to leave the connection to the database opened.

**Comment by skie** [comment]
If you set persistent param as true you got persistenace. In case of oci8 driver documentation says:

> Connecting to an Oracle server is a reasonably expensive operation in terms of the time that it takes to complete. The oci_pconnect() function uses a persistent cache of connections that can be re-used across different script requests. This means that the connection overhead will typically only occur once per PHP process (or Apache child).

Same would work if you use PHP-FPM.
