### ISSUE TITLE
Call Oracle Procedure with Array

### ISSUE THREAD

**Issue by bokuyami21** [CakeDC/cakephp-oracle-driver#13]
I wanna to passing array into my store procedure but there didnt appear to support.
Please teach me  how way i can pass through array into my store procedure.
Thanks and sorry for my poor English

**Comment by mthlabe** [comment]
Any help will be appreciated,

I'm getting the following error:

Fatal error: Class 'CakeDC\OracleDriver\Database\Type\CursorType' not found in C:\www\cake\vendor\cakephp\cakephp\src\Database\Type.php on line 107

**Comment by skie** [comment]
CursorType is present in repo. no new info.
