### ISSUE TITLE
SQL was generated from function OracleSchema.describeIndexSql error

### ISSUE THREAD

**Issue by bokuyami21** [CakeDC/cakephp-oracle-driver#15]
When i specified schema at Table with $this->table(SCHEMA.TABLENAME) and run.
It didnt work well.
When i debug it and see error when execute sql what was generated from function OracleSchema.describeIndexSql

**Comment by bokuyami21** [comment]
Sry i m version is too old.

**Comment by skie** [comment]
does it mean question is not actual any more?

**Comment by Megslalk** [comment]
Hi! Closing this issue - please re-open if you require additional assistance! Thanks!
