### ISSUE TITLE
Class CakeDC\OracleDriver\Database\Type\CursorType not found

### ISSUE THREAD

**Issue by NozX18** [CakeDC/cakephp-oracle-driver#24]
Hi,

I have installed OracleDriver in CakePHP 3 without composer because I can't use it in my work.

So when I copy package in CakePHP plugins folder i get error : Class 'CakeDC\OracleDriver\Database\Type\CursorType' not found.

I think it's a miss config in composer.json or another, I don't know ! 

Sorry for my bad English !

Thank you for your help !

**Comment by steinkel** [comment]
hi @NozX18 looks like the plugin is not loaded correctly as the class is present here https://github.com/CakeDC/cakephp-oracle-driver/blob/master/src/Database/Type/CursorType.php

How are you handling class loading if you are not using composer?

Thanks,

**Comment by NozX18** [comment]
Hi @steinkel and thank you for your answer.

I have download zip plugin and copied it to the cakephp plugins folder.

In bootstrap.php I added this code line : Plugin::load('CakeDC/OracleDriver', ['bootstrap' => true]);

Thanks,

**Comment by NozX18** [comment]
So I have resolved my problem. I finally used composer because my network administrator unlocked it on the firewall.

But I think that I would have copied the files in the cakephp vendor folder and update the file cakephp-plugins.php with this line : **'CakeDC/OracleDriver' => $baseDir . '/vendor/cakedc/cakephp-oracle-driver/'**,

Thank you for your help !
