### ISSUE TITLE
OracleOCI extension php

### ISSUE THREAD

**Issue by marouprod** [CakeDC/cakephp-oracle-driver#31]
Hello,

to connect to oracle database from my project cakephp, Im using CakeDC, it's working perfectly on windows, but not with centos

Database driver CakeDC\OracleDriver\Database\Driver\OracleOCI cannot be used due to a missing PHP extension or unmet dependency

> php -i |grep oci

/etc/php.d/oci8.ini,
/etc/php.d/pdo_oci.ini
oci8
oci8.connection_class => no value => no value
oci8.default_prefetch => 100 => 100
oci8.events => Off => Off
oci8.max_persistent => -1 => -1
oci8.old_oci_close_semantics => Off => Off
oci8.persistent_timeout => -1 => -1
oci8.ping_interval => 60 => 60
oci8.privileged_connect => Off => Off
oci8.statement_cache_size => 20 => 20
PDO drivers => pgsql, sqlite, sqlsrv, oci

can you help me please, I'm blocked since 2 days

**Comment by jmbIFR** [comment]
Hi,

Installing OCI8 on the web server have a requirement. You have to install an Oracle Instant client.
Read  http://php.net/manual/en/oci8.requirements.php for details

jm

**Comment by skie** [comment]
closing issue, as there is no more feedback
