### ISSUE TITLE
Lowercase column names

### ISSUE THREAD

**Issue by juniorionut** [CakeDC/cakephp-oracle-driver#32]
Hello,

How can i get the result sets having the column names in lowercase as i can't find in the docs?
 At this point i am using an external method that uses array_map and applies array_change_key_case to the array.
Thanks!

**Comment by juniorionut** [comment]
Hello,
Found that out on my own, use for "CakePHP" the following declaration:

            'encoding'      => 'utf8',
            'timezone'      => 'UTC',
            'flags'         => [
            	PDO::ATTR_CASE => PDO::CASE_LOWER
            ],

**Comment by monsurhoq** [comment]
@juniorionut after using `PDO::ATTR_CASE => PDO::CASE_LOWER` I'm getting below error:
```
Argument 1 passed to Cake\ORM\Entity::__construct() must be of the type array, bool given, called in D:\xampp\htdocs\ebl\skypay_mis\vendor\cakephp\cakephp\src\ORM\ResultSet.php on line 602
TypeError
[Documentation](https://book.cakephp.org/3/) [API](https://api.cakephp.org/)
Error in: ROOT\vendor\cakephp\cakephp\src\ORM\Entity.php, line 48
```
