### ISSUE TITLE
Cake\Database\Driver and Cake\Database\Driver\PDODriverTrait define the same property ($_connection)

### ISSUE THREAD

**Issue by jmbIFR** [CakeDC/cakephp-oracle-driver#33]
After update from cakephp 3.5 to 3.7.4, i have the following error

`Strict (2048): Cake\Database\Driver and Cake\Database\Driver\PDODriverTrait define the same property ($_connection) in the composition of CakeDC\OracleDriver\Database\Driver\OracleBase. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed [ROOT/vendor/cakedc/cakephp-oracle-driver/src/Database/Driver/OracleBase.php, line 297]`

using PHP 5.6.

The cakephp-oracle-driver can't execute  query with cakephp 3.7.4

**Comment by jmbIFR** [comment]
The commit 8d5f5c035e6532eebb63d2d5d5a7a2c000bc5e5a in master is not fully working with cakephp 3.6

I have made 2 commits for 3.6 and 3.7 compatibility
 
https://github.com/jmbIFR/cakephp-oracle-driver.

**Comment by skie** [comment]
resolved
