### ISSUE TITLE
insert or update in cakePHP 3.6

### ISSUE THREAD

**Issue by jmbIFR** [CakeDC/cakephp-oracle-driver#36]
The commit 8d5f5c035e6532eebb63d2d5d5a7a2c000bc5e5a merged in master for adding CakePHP 3.6 compatibility added a regression.
With the commit 8d5f5c035e6532eebb63d2d5d5a7a2c000bc5e5a only select statement can be done. Insert or update statements always fails.

From 8d5f5c035e6532eebb63d2d5d5a7a2c000bc5e5a
```php
-        if ($isObject && $query->bufferResults() === false || $disableBuffer) {
-            $statement->bufferResults(false);
+        if ($isObject && $query->isBufferedResultsEnabled() === false || $disableBuffer) {
+            $statement->enableBufferedResults(false);
```

The exepresion $query->bufferResults() should be replaced with $query->isBufferedResultsEnabled() in cakePHP 3.6

But $statement->enableBufferedResults(false) doesn't exist and  $statement->bufferResults(false); should be keep in place

**Comment by skie** [comment]
applied in 3.x branch
