### ISSUE TITLE
Does not generate relationships in the Model Table file

### ISSUE THREAD

**Issue by SandroNigro** [CakeDC/cakephp-oracle-driver#39]
I have two simple tables, the second is made with a foreign key to the first.
When I use "bake" to generate code in the "initialize" function, SecondTable file, I don't get, for example: $this->belongsTo('Firsts', [
 'foreignKey' => 'first_id'.
joinType' => 'INNER'
]) 
**Cakephp: 3.5**
The connection is ok, but no relationship is ever generated.
Can you suggest something to me?

**Comment by skie** [comment]
In tests diferent relations use cases are covered and working well
