### ISSUE TITLE
OracleOCI default configuration

### ISSUE THREAD

**Issue by jmbIFR** [CakeDC/cakephp-oracle-driver#41]
For OCI configuration $config['persistent'] and $config['encoding'] setting are ingnored.

As explain in #38 persistent and encoding setting can be defined in the $config['flags']['persistent'] and $config['flags']['charset'].

The default value for $_baseConfig['encoding'] => 'utf8' is never used and the charset default value for the connection is set to the database charset.

**Comment by skie** [comment]
applied for 4.0

**Comment by skie** [comment]
applied
