### ISSUE TITLE
"FROM DUAL" incorrectly appended when "from" at begin of line

### ISSUE THREAD

**Issue by ewbarnard** [CakeDC/cakephp-oracle-driver#43]
See `Database/Driver/OracleBase.php` line 175:

~~~~php
if (strpos($statement, 'select') !== 0 || preg_match('/ from /', $statement)) {
~~~~

When the "from" part of the query is at the start of a line (formatted for multiple lines), FROM DUAL is appended to the statement, causing the query to fail. I fixed the query by adding a space before `from`. We should be able to fix `OracleBase.php` by changing the regular expression to `/\sfrom\s/`, allowing any whitespace.

**Comment by skie** [comment]
applied for 4.0
