### ISSUE TITLE
Declaration of CakeDC\OracleDriver\Database\OracleConnection must be compatible with Cake\Database\Connection

### ISSUE THREAD

**Issue by linaresamado88** [CakeDC/cakephp-oracle-driver#45]
Fatal error: Declaration of CakeDC\OracleDriver\Database\OracleConnection::cacheMetadata($cache) must be compatible with Cake\Database\Connection::cacheMetadata($cache): void in /var/www/html/qreport_v2/vendor/cakedc/cakephp-oracle-driver/src/Database/OracleConnection.php on line 22

**Comment by skie** [comment]
Can you note what app version do you saying about?

**Comment by linaresamado88** [comment]
CakePHP 4.0.7

**Comment by ualisonaguiar** [comment]
Good afternoon.
I'm using cakephp in version 4.1.0 when trying to establish a connection returns the error message: Fatal error: Declaration of CakeDC\OracleDriver\Database\OracleConnection::cacheMetadata($cache) must be compatible with Cake\Database\Connection::cacheMetadata($cache): void in /vendor/cakedc/cakephp-oracle-driver/src/Database/OracleConnection.php on line 22.

I changed the cakephp version to 4.0.7 the error remains.

Can someone help me?

Here is the code used:

        $connection = \Cake\Datasource\ConnectionManager::get('EbCorp');
        debug($connection);
        die;

Thank you

**Comment by ualisonaguiar** [comment]
Good morning error resolved in version 5.0.

Thanks.
