### ISSUE TITLE
NLS_NUMERIC_CHARACTERS problem for ptBR Database

### ISSUE THREAD

**Issue by LeandroFranciscato** [CakeDC/cakephp-oracle-driver#46]
We're having problems using the driver with our database because of our numeric character configuration. I've found a solution [here](https://stackoverflow.com/questions/40914242/php-change-numbers-with-decimals-from-comma-to-dot) but it doesn't look good to change the plugin itself.

Is there a more organized solution for that? Using PDO maybe?

Thanks for the awesome plugin.

**Comment by skie** [comment]
what prevent you from defining 'init' settings inthe app.php in the Datasources driver configration block?

**Comment by LeandroFranciscato** [comment]
Yep, you're right, actualy we've done it already. Forgot to mention here, sorry.
Thanks for the reply.
