### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by augustosabino** [CakeDC/cakephp-oracle-driver#49]
Hello.

I'm starting to use the plug-in with Cakephp 4 and this is causing the problem below when accessing the user index:

**1. Notice (8): Undefined index: count [CORE\src\Database\FieldTypeConverter.php, line 127].**

And this error still occurs:

 **1. Argument 1 passed to Cake \ ORM \ Entity :: __ construct () must be of the type array, bool given, called in C: \ Developer \ xampp \ htdocs \ sispcmi \ vendor \ cakephp \ cakephp \ src \ ORM \ ResultSet.php on line 544**

Does anyone know what these problems can be and how to fix them ???

I tested with MySQL and the error does not occur.

Thanks.

**Comment by jmbIFR** [comment]
Hi,

I think this issue is related with issue #55

Can you try my fix :  https://github.com/jmbIFR/cakephp-oracle-driver/tree/5.x
