### ISSUE TITLE
5.x Always quote SELECT identifier for Oracle

### ISSUE THREAD

**Issue by jmbIFR** [CakeDC/cakephp-oracle-driver#55]
Oracle auto converts unquoted identifiers to upper case.
Unquoted select aliases brake the cakePHP camelCase table Alias.

cakePHP commit https://github.com/cakephp/cakephp/commit/4949b726074ddadbbdbe3e67b8cd7ffdbaed6ab4  "Quote SELECT identifiers only if autoquoting is enabled."

The postgres driver is modified to always apply select aliases https://github.com/cakephp/cakephp/commit/49608e98937de4f9e3b16d0c0743f7a24508a90d#diff-e71e42d8a65ac8e52edc9657223c9f8c  Always quote SELECT identifier for Postgres. 

The Oracle driver need the same modification as the postgres driver

**Comment by skie** [comment]
merged pr #56
